/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheButton: typeof import('./src/components/TheButton.vue')['default']
    TheDragSort: typeof import('./src/components/TheDragSort.vue')['default']
    TheDropdown: typeof import('./src/components/TheDropdown.vue')['default']
    TheFooter: typeof import('./src/components/TheFooter.vue')['default']
    TheHeader: typeof import('./src/components/TheHeader.vue')['default']
    TheLoading: typeof import('./src/components/TheLoading.vue')['default']
    TheModal: typeof import('./src/components/TheModal.vue')['default']
    TheNoData: typeof import('./src/components/TheNoData.vue')['default']
    TheSwitch: typeof import('./src/components/TheSwitch.vue')['default']
    TheTabs: typeof import('./src/components/TheTabs.vue')['default']
    TheTelescoping: typeof import('./src/components/TheTelescoping.vue')['default']
  }
}
